<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\Category;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            ['category_id' => 1, 'title' => 'Novel The Big Four (Empat Besar)', 'author' => 'Agatha Christie', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 1927, 'description' => '""" Di dalam gudang bawah tanah di East End itu, aku yakin inilah saat-saatku yang terakhir. Kusiapkan diriku menghadapi shock derasnya arus air yang hitam itu.

                Aku terkejut ketika mendengar tawa bernada rendah. ""Anda pemberani,"" kata laki-laki di sofa itu. ""Kami orang Timur menghargai keberanian. Anda telah berani menghadapi kematian Anda sendiri. Dapatkah Anda menghadapi kematian orang lain pula?""

                Dahiku bersimbah peluh.

                ""Pena sudah siap,"" kata laki-laki itu dengan tersenyum. ""Anda tinggal menulis. Kalau tidak...""

                ""Kalau tidak?"" tanyaku tegang.

                ""Kalau tidak, wanita yang Anda cintai akan mati... perlahan-lahan. Dalam waktu senggangnya, majikan kami suka menghibur diri dengan membuat alat-alat dan menciptakan cara-cara penyiksaan...."""', 'price' => 48000, 'stock' => 50, 'is_highlight' => 0, 'cover_image' => 'books/theBigFour.png'],
            ['category_id' => 1, 'title' => 'Cantik Itu Luka', 'author' => 'Eka Kurniawan', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2002, 'description' => 'Hidup di era kolonialisme bagi para wanita dianggap sudah setara seperti hidup di neraka. Terutama bagi para wanita berparas cantik yang menjadi incaran tentara penjajah untuk melampiaskan hasrat mereka. Itu lah takdir miris yang dilalui Dewi Ayu, demi menyelamatkan hidupnya sendiri Dewi harus menerima paksaan menjadi pelacur bagi tentara Belanda dan Jepang selama masa kedudukan mereka di Indonesia.', 'price' => 87500, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/cantikItuLuka.png'],
            ['category_id' => 1, 'title' => 'Komik 10 Sahabat Dijamin Masuk Surga', 'author' => 'Izzah Annisa', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2017, 'description' => 'Di masa perkembangannya, Islam mendapat ujian yang sangat berat. Bermacam-macam gangguan bahkan siksaan kerap dialami kaum muslimin. Apakah mereka menyerah? Tidak. Dengan keteguhan iman dan tekad yang kuat, mereka bersama Rasulullah SAW tak lelah berjuang menegakkan panji-panji Islam di muka bumi. Di antara mereka ada sepuluh sahabat Rasulullah SAW yang dijanjikan surga oleh Allah SWT.
                Para sahabat Nabi adalah manusia-manusia pilihan Allah sesudah para Nabi dan Rasul. Allah menjelaskan keutamaan para sahabat Nabi dibandingkan dengan manusia yang lainnya. Di antara para sahabat Nabi, yang paling utama adalah sepuluh sahabat yang dijamin masuk surga.
                Komik ini bercerita tentang kisah hebat para pejuang Islam sekaligus tokoh penting di masa-masa awal perkembangannya. Sepuluh sahabat Rasulullah SAW yang istimewa ini adalah sosok-sosok yang sholeh, kuat, tangguh dan tentunya juga sangat cerdas. Mereka gigih berjuang dan rela berkorban baik harta maupun jiwa demi tegaknya panji-panji Islam. Teladan utama ada pada sosok-sosok yang diceritakan dalam komik ini dan akan menyadarkan kita tentang berbagai sisi kemuliaan dan keteladanan yang baik dari mereka.', 'price' => 88200, 'stock' => 100, 'is_highlight' => 1, 'cover_image' => 'books/sahabatDijaminMasukSurga.png'],
            ['category_id' => 1, 'title' => 'Komik Next G: Perpustakaan Angker', 'author' => 'Humaira Via Nur Aini dkk', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Nisa mengajak sepupunya, Rafa, untuk mengunjungi perpustakaan kota. Tapi, tujuan mereka ke sana bukan untuk membaca atau meminjam buku, melainkan untuk membuktikan keangkeran gedung perpustakaan. Benarkah akan ada penampakan yang muncul di hadapan mereka atau ini hanya rumor belaka?', 'price' => 39000, 'stock' => 40, 'is_highlight' => 0, 'cover_image' => 'books/perpustakaanAngker.png'],
            ['category_id' => 1, 'title' => 'Komik Baik: Petualangan di Negeri Piramida', 'author' => 'Rizki Ayu Amaliah', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Alifah dan Uzair pindah ke Mesir karena mengikuti ayah yang sedang bersekolah di Kairo, Mesir. Di Mesir, mereka bertualang mengunjungi tempat-tempat bersejarah. Banyak kisah yang didapat saat bertualang di sana. Mereka juga mendapatkan pelajaran tentang nasihat Lukmanul Hakim yang disebutkan dalam Al-Qur’an dari petualangan mereka di negeri piramida. Nasihat Lukmanul Hakim, diantaranya: menyekutukan Allah adalah perbuatan dosa besar, perbuatan sekecil apa pun akan dibalas oleh Allah Swt., nasihat untuk mendirikan salat dan berbuat baik kepada orang tua.', 'price' => 45000, 'stock' => 20, 'is_highlight' => 0, 'cover_image' => 'books/petualanganDiNegeriPiramida.png'],
            
            ['category_id' => 2, 'title' => 'Al Quran Tajwid Warna As-Samad Besar /Hc', 'author' => 'Depag', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2014, 'description' => 'Keterangan Isi Kitab : Pedoman transliterasi Arab-Latin, Tajwid warna, Tanda Waqaf, Tanda Sifir, Daftar Ayat Sajdah, Doa Sujut Tilawah, Daftar Surah, Panduan Hukum Tajwid, Adab Membaca Al-Quran', 'price' => 107100, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/alQuran.png'],
            ['category_id' => 2, 'title' => 'Tafsiran Alkitab Bagi Orang Percaya, Perjanjian Baru. Buku 1 (Matius - Kisah Para Rasul)', 'author' => 'William MacDonald', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Tafsiran Alkitab Bagi Orang Percaya mengeksplorasi makna yang lebih dalam dari setiap kitab dalam Perjanjian Baru dan menangani isu-isu kontroversial dari sudut pandang konservatif secara teologis sembari menghadirkan pandangan-pandangan alternatif. Melayani sebagai pengantar yang menyenangkan untuk studi Alkitab, buku ini memberikan kejelasan dan konteks tulisan suci dalam bahasa yang mudah dipahami.', 'price' => 330000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'bookstafsiranAlkitab.png/'],
            ['category_id' => 2, 'title' => 'Sebab Bahagia Itu Mudah', 'author' => 'Khaliel Anwar', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2017, 'description' => 'Rapuh, lemah dan tak berdaya sangat identik dengan makhluk. Merasa rapuh tak berdaya akan membuat orang selalu bahagia ketika perasaan itu mendorong Anda menambatkan dan menyandarkan hidup kepada Allah. Bukankah hanya orang yang bersandar (bertawakal) kepada Allah yang bakal dianugerahi kekukuhan dan kekuatan luar biasa? Kesadaran sebagai yang lemah dan rapuh ini merupakan pengakuan atas apa yang disifatkan Allah pada manusia dalam firman-Nya. Karena, itu berasal dari Yang Mahabaik. Bukankah teko berisi susu hanya akan mengeluarkan susu? Dan, Allah adalah kebaikan mutlak, tak ada yang mengalir dari-Nya, kecuali kebaikan. Ya … isi segenap realitas itu hanya kebaikan. Tak ada selain itu.', 'price' => 49500, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/bahagiaMudah.png'],
            ['category_id' => 2, 'title' => 'Indahnya Kematian', 'author' => 'Mikail Konsu', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Indahnya Kematian: Menjemput Husnul Khotimah dengan Hati Tenang adalah sebuah karya yang mengajak pembaca untuk memandang kematian bukan sebagai akhir yang menakutkan, tetapi sebagai pintu gerbang menuju kehidupan abadi yang lebih baik. Buku ini menyuguhkan pendekatan spiritual yang lembut dan penuh harapan, membimbing hati agar siap menghadapi kematian dengan tenang, ikhlas, dan penuh persiapan.', 'price' => 59000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/indahnyaKematian.png'],
            ['category_id' => 2, 'title' => 'Zikir dan Doa Setelah Shalat: Dilengkapi Penjelasan Berdasarkan Al-Qur’an dan Hadis', 'author' => 'Hamdan Hamedan', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Ketika ditanya terkait kapan waktu mustajab untuk berdoa, Rasulullah saw. menjawab, “Doa di tengah malam terakhir dan akhir shalat wajib.” (HR. Tirmidzi.) Hal ini menunjukkan betapa pentingnya berzikir dan berdoa setelah shalat, karena doa adalah jantung ibadah itu sendiri. Buku Zikir dan Doa Setelah Shalat menyajikan kumpulan doa dan zikir yang shahih, lengkap dengan terjemahan dan penjelasan maknanya. Diharapkan buku ini dapat menjadi tuntunan yang praktis bagi para pembaca dalam melafalkan doa-doa dan zikir setelah shalat.', 'price' => 45000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/zikirDoaSetelahSolat.png'],

            ['category_id' => 3, 'title' => 'Witch Bakery: Toko Roti Pengantar Jiwa', 'author' => 'Han Su-in', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Ke manakah perginya arwah hewan yang sudah mati? Sebuah toko roti aneh menawarkan pekerjaan kepada Lala yang sudah berkali-kali ditolak saat mencari pekerjaan paruh waktu. Ternyata, toko roti itu merupakan pemberhentian sementara para arwah hewan sebelum menuju dunia bawah. Berbagai arwah datang dengan harapan mewujudkan keinginan terakhir mereka dengan pemilik sebelumnya.', 'price' => 88000, 'stock' => 60, 'is_highlight' => 0, 'cover_image' => 'books/witchBakery.png'],
            ['category_id' => 3, 'title' => 'The Goodbye Cat', 'author' => 'Arikawa Hiro', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Di balik pergantian musim, seekor anak kucing. yang baru saja diselamatkan dari tempat sampah, mengajarkan seorang lelaki bagaimana menjadi ayah yang baik untuk bayinya sendiri. Kita juga akan bertualang ke pulau kucing, bertemu dengan sekelompok kucing liar yang mengajarkan seorang anak laki-laki untuk tidak mengganggu alam.', 'price' => 109000, 'stock' => 80, 'is_highlight' => 1, 'cover_image' => 'books/goodbyeCat.jpeg'],
            ['category_id' => 3, 'title' => 'Toko yang Buka di Kala Hujan', 'author' => 'You Yeong-Gwang', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Selamat datang di Toko Musim Hujan! Sebagai pertokoan terhormat yang menjunjung tinggi kejujuran dan kepercayaan, kami ingin mengajukan penawaran istimewa kepada Anda. Apakah Anda ingin menjual kemalangan Anda? Kami akan memberi Anda kesempatan untuk menukarkannya dengan kebahagiaan yang tersedia di toko. Namun, kami tidak bertanggung jawab atas apa pun yang terjadi selama Anda berada di sini.', 'price' => 74250, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/tokoHujan.png'],
            ['category_id' => 3, 'title' => 'Piranesi', 'author' => 'Susanna Clarke', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Sejak Dunia berawal, dipastikan ada 15 orang yang eksis:

                ORANG PERTAMA: DIRIKU
                Aku yakin aku berusia antara 30–35 tahun. Tinggiku kira-kira 183 cm dan tubuhku bertipe ramping.

                ORANG KEDUA: YANG LAIN
                Aku memperkirakan umur Yang Lain sekitar 50–60 tahun. Dia seorang ilmuwan sepertiku dan satu-satunya manusia lain yang masih hidup. Piranesi. Seperti itulah dia memanggilku. Yang terasa aneh karena sejauh yang kuingat, itu bukan namaku.

                ORANG KETIGA SAMPAI KELIMA BELAS
                Kerangka-kerangka yang kutemukan di berbagai Aula dalam berbagai kondisi.', 'price' => 94000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/piranesi.png'],
            ['category_id' => 3, 'title' => 'Kota Seribu Lantai', 'author' => 'Dewi Infan', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Erin, seorang perempuan yatim piatu pekerja kantoran yang tinggal bersama adiknya, usai ditinggal pergi Kakek yang menjaga mereka sedari kecil untuk selama-lamanya. Demi memenuhi kebutuhan hidup dan menabung untuk biaya kuliah adik, Erin melupakan hasratnya untuk keluar, dengan menyibukkan diri di kantor bersama sahabainya, sembari berhadapan dengan Pak Bos yang kerap memarahi dan menegurnya.', 'price' => 86000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/kotaSeribuLantai.png'],

            ['category_id' => 4, 'title' => 'The Master TKA+US SD/MI 2025-2026', 'author' => 'Tim Tentor Selasar', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Buku The Master TKA+US SD/M 2025-2026 ini berisi materi dan latihan soal-soal yang diharapkan dapat membantu siswa dalam mencapai prestasi belajar yang memuaskan serta menjadi pribadi yang berkarakter, di samping membantu guru dalam proses belajar mengajar di sekolah.', 'price' => 149000, 'stock' => 60, 'is_highlight' => 0, 'cover_image' => 'books/tkaSd.png'],
            ['category_id' => 4, 'title' => 'The Master TKA+US SMP/MTs 2025-2026', 'author' => 'Tim Tentor Selasar', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Seluruh tipe soal TKA dibahas mendalam, sehingga kamu bisa memahami pola soal dan percaya diri menghadapi ujian. Materi inti disajikan secara ringkas dan praktis, cocok untuk belajar cepat tanpa ribet. Disusun sesuai kisi-kisi dan standar terbaru, sehingga latihan soal benar-benar relevan dengan ujian sesungguhnya. Setiap soal dijelaskan langkah demi langkah dengan metode tentor berpengalaman, membuat belajar jadi lebih mudah.', 'price' => 149000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/tkaSmp.png'],
            ['category_id' => 4, 'title' => 'TKA Matematika Untuk Siswa SMA-MA/SMK-MAK', 'author' => 'Marthen Kanginan', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Buku TKA Mata Pelajaran Wajib Matematika untuk Siswa SMA-MA/SMK-MAK ini dirancang sebagai bekal strategis bagi siswa kelas 12 dalam menghadapi Tes Kemampuan Akademik (TKA). Dengan materi yang ringkas namun lengkap, soal-soal yang variatif, dan pembahasan yang tajam dan mudah dipahami, siswa dapat belajar secara efektif dan efisien. Buku ini dapat digunakan untuk belajar mandiri, berlatih secara intensif, ataupun sebagai pendamping di sekolah.', 'price' => 83000, 'stock' => 35, 'is_highlight' => 1, 'cover_image' => 'books/tkaMtkSma.png'],
            ['category_id' => 4, 'title' => 'Step by Step Skripsimu', 'author' => 'Dr. Ira Mirawati, M.Si.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Selamat memegang buku Step by Step Skripsimu. Buku yang dihadirkan khusus untuk membantu menemani kalian berjuang menyelesaikan tugas akhir atau skripsi. Sebuah buku yang dituliskan berdasarkan pengalaman selama menjadi dosen, yang mendampingi mahasiswa melalui proses skripsinya.', 'price' => 83000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/stepByStepSkripsi.png'],
            ['category_id' => 4, 'title' => 'Universitas Terbuka 39 Tahun Bertransformasi', 'author' => 'Ty Harijono', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Kali ini derap langkah Universitas Terbuka dalam mencerdaskan bangsa, dilihat dari perspekstif yang berbeda. Harian Kompas yang selama ini mengikuti, mempublikasikan dan ikut mendokumentasikan berbagai aktivitas Universitas Terbuka, menuangkan pandangannya dalam bentuk sebuah buku. Sumber buku sebagian besar berasal dari catatan dan tulisan wartawan, serta foto yang didokumentasikan Harian Kompas. Dokumentasi tidak hanya dilakukan sejak Universitas Terbuka berdiri tahun 1984, tetapi jauh ketika sistem pembelajaran jarak jauh masih berupa gagasan di tahun 1950-an. Gagasan yang dinarasikan kemudian diuji coba dan akhirnya diwujudkan dalam bentuk Universitas Terbuka.', 'price' => 99000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/universitasTerbuka.png'],

            ['category_id' => 5, 'title' => 'Atomic Habits', 'author' => 'James Clear', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2020, 'description' => 'Perubahan Kecil, Hasil Luar Biasa!
                Jika Anda kesulitan mengubah kebiasaan, masalahnya bukan Anda. Masalahnya adalah sistem Anda. Kebiasaan buruk berulang lagi dan lagi bukan karena Anda tidak ingin berubah, tetapi karena Anda memiliki sistem perubahan yang salah. Anda tidak naik ke tingkat tujuan Anda. Anda jatuh ke tingkat sistem Anda. Di sini, Anda akan mendapatkan sistem terbukti yang dapat membawa Anda ke tingkat yang lebih tinggi.', 'price' => 335000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/atomicHabits.png'],
            ['category_id' => 5, 'title' => 'Is It Bad or Good Habits', 'author' => 'Sabrina Ara', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2021, 'description' => 'Sadarkah Anda yang membawa langkah Anda ke dalam lobang yang sama tersebut adalah kebiasaan yang serupa? Ibarat sebuah perjalanan, proses kebiasaan yang berulang akan menghasilkan akhir yang sama. Otak kita dalam alam bawah sadarnya telah merekam memori dengan peristiwa-peristiwa serupa di mana itu terbentuk dari tangkapan rutinitas yang dijalani, yakni kebiasaan kita.', 'price' => 47000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/goodBadHabits.png'],
            ['category_id' => 5, 'title' => 'Life Reset: Bertumbuh Dimulai dari Sini', 'author' => 'Senja Rindiani', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Pembahasan dalam buku ini dikemas dalam lima bagian, termasuk juga tambahan bagian worksheet dan rekomendasi buku. Untuk memulai perjalanan yang terjal, kamu perlu belajar memaafkan diri dulu supaya siap menghadapi rintangan ke depannya.', 'price' => 68600, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/lifeReset.png'],
            ['category_id' => 5, 'title' => 'Professional Public Speaking Guide', 'author' => 'Gewa Deara', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Buku ini adalah panduan public speaking yang ditulis dengan gaya hangat, jujur, dan praktis. Bukan sekadar teori, buku ini mengupas tuntas hal-hal yang sering luput dari buku public speaking konvensional—seperti kenapa lidah bisa mendadak kaku, kenapa tangan dingin waktu presentasi, dan kenapa perfeksionisme sering bikin pesan tidak sampai.', 'price' => 59000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/publicSpeaking.png'],
            ['category_id' => 5, 'title' => 'Stop Bullying', 'author' => 'Tia Rifianty', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => '"Ah, cuma bercanda kok!" Tapi kamu tidak tahu, di balik tawa yang dipaksakan, ada hati yang remuk. Di balik diamnya seseorang, ada luka yang tak terlihat Bullying bukan selalu soal fisik. Kata-kata yang merendahkan, ejekan yang diulang-ulang, atau candaan yang menyakit — semuanya bisa menjadi bentuk kekerasan yang membekas lama dalam jiwa.', 'price' => 59000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/stopBullying.png'],

            ['category_id' => 6, 'title' => 'Excel Hack: Bagaimana Mengubah Data Menjadi Chart dan Storytelling yang Praktis', 'author' => 'Jubilee Enterprise', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => '"Rahasia Visualisasi Data dan Storytelling dalam Satu Buku!". Bayangkan bisa mengubah angka-angka di spreadsheet menjadi visualisasi memukau dan cerita yang menggugah aksi—semua tanpa perlu software rumit atau proses yang membingungkan. Buku ini hadir sebagai panduan lengkap dan praktis untuk membantu Anda menguasai visualisasi data dan storytelling langsung dari Excel yang Anda gunakan sehari-hari. Dengan teknik mulai dari bar chart hingga heat map, radar chart, bahkan fitur interaktif seperti scroll dan zoom, Anda akan belajar menciptakan grafik yang bukan hanya indah tapi juga bermakna.', 'price' => 111000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/excelHack.png'],
            ['category_id' => 6, 'title' => 'Mahir Olah Data Dengan SPSS', 'author' => 'Raka Satria Anugrah Dini', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Statistical Package for the Social Sciences atau biasa disebut SPSS, merupakan satu perangkat statistik yang paling populer digunakan di kalangan akademisi, peneliti, hingga profesional di berbagai bidang. SPSS ini dirancang untuk memudahkan analisis data dengan menyediakan antarmuka pengguna yang intuitif dan alat analisis yang canggih.', 'price' => 75500, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/spss.png'],
            ['category_id' => 6, 'title' => 'Data Science Menggunakan Bahasa R : Deep Learning', 'author' => 'Dr. Adi Nugroho, S.T., M.M.S.I.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Data Science merupakan suatu bidang ilmu yang (relatif) baru di Indonesia, tujuan utamanya adalah memahami dan menganalisis segala fenomena yang berkaitan dengan data yang bertipe terstruktur, semiterstruktur, serta tidak terstruktur, yang datang dari berbagai sumber data/data source yang sangat beragam (meskipun saat ini sumber data yang terutama berasal dari Big Data dan loT/Internet of Things) menggunakan pengetahuan yang terutama matematika, statistika, ilmu informasi (information science), serta ilmu komputer (terutama kecerdasan buatan/AI-Artificial Intelligence).', 'price' => 116000, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/dataScience.png'],
            ['category_id' => 6, 'title' => 'Teknik Dasar Menguasai Adobe After Effects Untuk Pemula', 'author' => 'M. Dzakwan Havi, S.Ds', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Apakah Anda seorang ilustrator atau animator yang sedang mencari aplikasi terbaik untuk membuat gambar dan animasi yang luar biasa? Jika iya, Anda bisa menggunakan Adobe After Effects. Dengan berbagai tools-nya, Anda akan lebih mudah dan terorganisasi dalam membuat gambar dan animasi yang menakjubkan.', 'price' => 55500, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/afterEffect.png'],
            ['category_id' => 6, 'title' => 'Rahasia Cara Buat Website Harga Jutaan', 'author' => 'Su Rahman', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2024, 'description' => 'Ada banyak cara membuat website, buku Rahasia Cara Buat Website Harga Jutaan ini adalah panduan lengkap membuat website paling gampang, Anda akan dipandu langkah demi langkah untuk bisa membuat website sendiri. Pembahasan dikemas dengan bahasa yang sederhana sehingga mudah untuk dipahami pemula. Berbasis WordPress dan Page Builder, Anda akan mampu membuat website layaknya profesional.', 'price' => 75600, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/caraBuatWebsite.png'],

            ['category_id' => 7, 'title' => 'Pengantar Ilmu Peternakan', 'author' => 'Prof. Ir. I Ketut Gede Wiryawan B.Sc., M.Ag.Sc., Ph.D.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2024, 'description' => 'Secara tekhnis, bahan kajian dalam buku ini tercakup dalam sepuluh Bab, diawali dengan uraian umum peran peternakan dalam masyarakat, domestikasi dan sejarah peternakan, ternak dan lingkungannya, tingkah laku dan kesejahteraan hewan ternak, dilajutkan dengan uraian umum mengenai peternakan unggas, babi, kuda, kambing dan domba, dan peternakan sapi dan kerbau.', 'price' => 115000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/peternakan.png'],
            ['category_id' => 7, 'title' => 'Burung-Burung dalam Tinjauan Budaya Mbaham Matta, Fakfak', 'author' => 'Domianus Tuturop, dkk.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Unik dan menarik jadi sebutan yang identik dengan tradisi dan budaya orang Papua. Namun predikat itu tidak hanya melekat pada kebiasaan turun-menurun yang dijalankan oleh masyarakat di kepulauan yang disebut sebagai surga kecil yang jatuh ke bumi itu. Penghuni lain yang tinggal di pulau inipun lekat dengan sebutan itu. Tak terkecuali burung-burung yang berdiam di Kabupaten Fakfak, Papua Barat.', 'price' => 170000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/burung.png'],
            ['category_id' => 7, 'title' => 'Rahasia Sukses Budidaya Ikan Patin Secara Intensif', 'author' => 'Hadi Tribowo', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Ikan patin merupakan salah satu ikan air tawar yang paling banyak dibudidayakan di Indonesia. Hewan ini diminati oleh konsumen di dalam dan luar negeri. Sayangnya, produksi ikan patin untuk tujuan ekspor masih terlalu kecil jika dibandingkan dengan peluang yang ada. Padahal salah satu habitat asli ikan ini ada di Indonesia dan perairan yang dapat dijadikan tempat budidaya begitu luas. Kita bisa saja mengambil jalan pintas dengan menangkap dan menjual ikan patin liar yang hidup di sungai-sungai besar. Dalam jangka pendek, mungkin saja menguntungkan karena tidak perlu mengeluarkan tenaga dan biaya pemeliharaan. Meskipun demikian, dalam jangka panjang aktivitas ini dapat merugikan. Jumlahnya akan cepat berkurang dan lama-kelamaan akan sulit dicari. Supaya ikan patin tetap lestari, perlu dilakukan budidaya di kolam-kolam buatan maupun di keramba. Jenis budidayanya tidak hanya pembesaran, melainkan juga mencakup produksi bibit.', 'price' => 37500, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/budidayaPatin.png'],
            ['category_id' => 7, 'title' => 'Buku Pintar Teknik Produksi Benih Ikan, Berdasarkan Cara Pembenihan Ikan yang Baik', 'author' => 'Hardaningsih', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Buku yang berjudul Teknik Produksi Benih ditulis oleh beberapa praktisi pembenih ikan baik yang bekerja di swasta atau institusi negeri bahkan pengusaha di bidang pembenihan ikan secara pribadi. Materi yang disampaikan pada buku ini dituliskan berdasarkan pengalaman yang telah dijalani. Komoditas ikan terdiri dari jenis ikan air tawar baik ikan konsumsi maupun ikan hias. Jenis ikan adalah jenis yang sudah banyak dikenal dan bahkan merupakan ikan ekonomis penting atau yang permintaan pasarnya tinggi.', 'price' => 162000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/produksiBenihIkan.png'],
            ['category_id' => 7, 'title' => 'Pedoman Sukses Budi Daya Ikan Lele', 'author' => 'Hadi Tribowo', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2022, 'description' => 'Kesuksesan budidaya ikan lele setidaknya dipengaruhi oleh bibit, tempat pemeliharaan, pakan, serta pencegahan dan penanggulangan penyakit. Bibit ikan lele yang ditebar harus yang kualitasnya baik dan varietasnya sesuai dengan tempat pemeliharaannya. Tempat pemeliharaan ikan lele dapat berupa kolam, keramba, maupun sawah dengan sistem minapadi. Jenis, kualitas, kuantitas, dan intensitas pakan juga perlu diperhatikan untuk mengoptimalkan pertumbuhan ikan berkumis tersebut. Faktor lain yang tidak kalah pentingnya adalah cara mencegah dan menanggulangi penyakit yang mungkin menyerang ikan lele yang sedang dibudidayakan.', 'price' => 47000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/budidayaLele.png'],

            ['category_id' => 8, 'title' => 'Morfologi Kota: Pengantar Studi Bentuk Fisik Kota', 'author' => 'Ardy Maulidy Navastara, dkk.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Buku ini menawarkan pemahaman mendalam tentang morfologi kota, yaitu studi mengenai bentuk fisik kota dan bagaimana bentuk tersebut terbentuk dan berkembang dari waktu ke waktu. Pembaca akan diajak untuk mengenal konsep dasar morfologi kota, termasuk definisi, sejarah, serta prinsip-prinsip yang mendasarinya.', 'price' => 158000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/morfologiKota.png'],
            ['category_id' => 8, 'title' => 'Perencanaan Tapak Berkelanjutan: Teori dan Aplikasi', 'author' => 'Prananda Navitas, dkk.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Perencanaan Tapak Berkelanjutan: Teori dan Aplikasi adalah buku ajar yang dirancang untuk memberikan pemahaman mendalam tentang prinsip dan teknik perencanaan tapak dalam konteks perencanaan kawasan dan perkotaan. Buku ini terdiri dari beberapa bab yang mencakup proses perencanaan tapak, analisis data internal dan eksternal tapak, metode analisis tapak, perumusan konsep tapak, serta penyusunan rekomendasi kesesuaian tapak. Setiap bab disusun secara sistematis untuk membantu pembaca memahami dan menerapkan konsep-konsep perencanaan tapak secara efektif.', 'price' => 188000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/tapakBerkelanjutan.png'],
            ['category_id' => 8, 'title' => 'Membangun Peradaban Dunia', 'author' => 'UNTUNG WIDYANTO, DKK.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Taman Ismail Marzuki yang dibangun tahun 1968 diniatkan sebagai pusat kesenian yang bebas dari intervensi kekuasaan. Para seniman tidak ingin diatur-atur oleh partai dan penguasa politik seperti yang terjadi di era Demokrasi Terpimpin. Periode Gubernur Ali Sadikin, TIM benar-benar menjadi ekosistem kesenian yang menggairahkan seniman dengan karya-karyanya yang fenomenal.', 'price' => 99000, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/membangunPeradabanDunia.png'],
            ['category_id' => 8, 'title' => 'Merancang Bangunan Sekolah', 'author' => 'Ir. Taufik Priambodo', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2024, 'description' => 'Sudah merupakan satu hal yang pasti, bahwa merancang arsitektur bangunan sekolah tidak lebih sulit dari merancang rumah besar. Memang luas bangunannya berada jauh di atas bangunan rumah besar yang hanya kisaran 300 m2. Namun, sebetulnya dari segi luas bangunan yang jauh lebih besar dari rumah mewah, sebagian besar luas bangunan sekolah hanyalah akumulasi dari luas jenis ruang kelas teori. Satu ruang kelas teori sekurang-kurangnya berukuran 42,25 m2 atau seukuran dengan 3,5 kali ruang tidur anak (4 m × 3 m) di bangunan rumah mewah.', 'price' => 60000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/membangunSekolah.png'],
            ['category_id' => 8, 'title' => 'Buku Ajar Interior: Azas Lingkungan Dalam', 'author' => 'DYAN AGUSTIN; NINIEK ANGGRIANI', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2021, 'description' => 'Pembelajaran interior merupakan pembelajaran yang fokus kepada bagian dalam dari suatu bangunan dan terlahir dari proses perkembangan kompleksitas Arsitektur. Mata kuliah Interior ini adalah mata kuliah praktek yang mengubah ide dan gagasan ruang sebagai bekal landasan dasar bagi mahasiswa dalam merancang selanjutnya.', 'price' => 143000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/interior.png'],

            ['category_id' => 9, 'title' => 'Buku Pedoman Tata Laksana Akupunktur pada Kasus Kanker di Fasilitas Pelayanan Kesehatan', 'author' => 'Wahyuningsih Djaali, Yoshua Viventius', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2021, 'description' => 'Ilmu akupunktur medik sampai dengan saat ini masih terus mengalami perkembangan dan sudah cukup dikenal oleh masyarakat luas. Saat ini, pelayanan akupunktur ini sudah mulai diaplikasikan di berbagai macam bidang ilmu, sebut saja seperti ilmu penyakit dalam, ilmu penyakit syaraf, ilmu kebidanan dan penyakit kandungan, ilmu penyakit syaraf, serta berbagai macam penyakit lainnya termasuk juga kanker.', 'price' => 75000, 'stock' => 60, 'is_highlight' => 0, 'cover_image' => 'books/akupuntur.png'],
            ['category_id' => 9, 'title' => 'Kesehatan, Olah Raga & Kinerja', 'author' => 'Santosa Giri Wijoyo', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2020, 'description' => 'Kesehatan Olahraga adalah sekumpulan ilmu-ilmu yang membahas segala permasalahan kesehatan yang berkaitan dengan olahraga. Artinya, kesehatan olahraga meliputi ilmu-ilmu kedokteran yang bertujuan memelihara kesehatan atlet dan kesehatan masyarakat pelaku olahraga, disertai dengan upaya memperbaiki penampilannya.', 'price' => 206000, 'stock' => 80, 'is_highlight' => 1, 'cover_image' => 'books/kesehatanOlahraga.png'],
            ['category_id' => 9, 'title' => 'Peran Dokter Gigi atasi gangguan ngorok dan OSA', 'author' => 'Prof. Drg. Laura Susanti Himawan, Sp.Pros(K), FICD', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'OSA atau Obstructive Sleep Apnea adalah salah satu gangguan tidur yang SA atau gejala utamanya adalah ngorok dan berhentinya napas secara berulang selama tidur. Jika tidak segera dirawat, OSA bisa memberi dampak buruk pada kondisi kesehatan kita, antara lain munculnya penyakit kardiovaskular.', 'price' => 120000, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/dokterGigi.png'],
            ['category_id' => 9, 'title' => 'Kesehatan Gigi dan Mulut Edisi Revisi', 'author' => 'drg. Siti Yundali Hongini Dr. Mac Aditiawarman, S.H., M. Hum.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2024, 'description' => 'Buku Kesehatan Gigi dan Mulut ini terbit karena terinspirasi oleh banyaknya masyarakat yang tidak peduli akan kesehatan gigi mereka. Mereka akan membutuhkan dokter gigi apabila mereka sudah mengalami masalah dengan gigi mereka. Mereka mecoba mengobatinya dengan meminum obat di warung atau membiarkan gigi mereka sedemikian rupa, sehingga setelah parah baru mereka datang ke dokter gigi.', 'price' => 105000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/kesehatanGigi.png'],
            ['category_id' => 9, 'title' => 'Endometriosis Fakta di Balik Kisah Nyeri Haid dan Infertilitas yang Membayangi Perempuan', 'author' => 'dr. Caroline Tirtajasa, Sp.OG.(K)', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Nyeri Haid Bukan Hal Biasa – Waspadai Endometriosis Sejak Dini Banyak perempuan terbiasa menahan nyeri saat haid karena mengira itu hal yang normal. Namun, ketika rasa sakit ini sampai menghalangi aktivitas, bisa jadi itu bukan nyeri haid biasa—melainkan tanda dari endometriosis. Sayangnya, karena anggapan "itu wajar", banyak perempuan tidak segera memeriksakan diri. Padahal, endometriosis bisa menyebabkan masalah serius seperti sulit hamil, perlengketan organ, bahkan menyebar ke luar sistem reproduksi.', 'price' => 90000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/endometriosis.png'],

            ['category_id' => 10, 'title' => 'Farm Bigbook: Budi Daya Sayuran Indigenous di Kebun dan Pot', 'author' => 'Hieronymus Budi Santoso', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Apa itu sayuran indigenous (baca: indijenes)? Arti kata indigenous, menurut Echols dan Shadily (1996), adalah asli atau pribumi. Sedangkan menurut Badan Penelitian dan Pengembangan Pertanian, sayuran indigenous adalah spesies sayuran asli Indonesia yang berasal dan daerah/wilayah/ekosistem tertentu, termasuk spesies pendatang dari wilayah geduras lam tetap telah berevolusi dengan iklim dan geografis wilayah Indonesia.', 'price' => 185500, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/saturanIndigenous.png'],
            ['category_id' => 10, 'title' => 'Untung Berlipat dari Budi Daya Jamur Tiram', 'author' => 'Netty Widyastuti', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Jamur sebagai bahan makanan, banyak mengandung nutrisi dan vitamin penting, seperti tiamin (vitamin B-1), riboflavin (vitamin B-2), niasin, biotin, dan sebagainya. Di samping itu, kandungan polisakarida dan ikatan protein tertentu telah terbukti dapat meningkatkan kesehatan manusia, antara lain anti kolesterol, antihipertensi, antikanker, meningkatkan stamina dan kebugaran tubuh. Jamur edible tidak hanya dapat dikonsumsi langsung, tetapi juga dapat didiversifikasi menjadi jamur awetan hingga bahan campuran kosmetik dan obat-obatan. Dengan teknologi rekayasa lingkungan dengan biaya yang tidak terlalu besar, organisme non klorofil ini dapat dikembangkan secara massal.', 'price' => 124000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/jamurTiram.png'],
            ['category_id' => 10, 'title' => 'Membuat Anggur Unggul Rajin Berbuah', 'author' => 'Yuno Ahmad Maulana', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Buah anggur bukan asli tanaman Indonesia, tapi hampir sem tahu apa itu anggur, meski belum tentu perna mencicipi rasanya, merasakan sensasi memetik buahnya. Apalagi memetik buah anggur di halaman rumah sendiri. Sayang sekali, stigma sulit, lama berbuah, ribet, banyak hama penyakit, dan hal jelek lain tentang budidaya Anggur sudah kadung terbentuk di keluarga Indonesia. Padahal yang betul itu, Indonesia tanah surga (kata band Koes Plus), dengan iklim dua musim dan tanahnya yang subur sejatinya Anggur akan berkembang baik seperti di surga.', 'price' => 88000, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/membuatAnggur.png'],
            ['category_id' => 10, 'title' => 'Panen Hidroponik Buah & Sayuran Buah Di Halaman Rumah', 'author' => '-', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2017, 'description' => 'Menanam buah dengan sistem Hidroponik. Kenapa tidak? Bagi Anda yang sudah melakoni hobi hidroponik sayuran, tentu ingin juga bertanam tanaman yang lain. Dengan sistem hidroponik, tidak hanya sayuran, tetapi buah dan sayuran buah juga bisa ditanam. Bagaimana teknis dan perlakuan bertanam buah dan sayuran buah secara hidroponik? Simak penjelasannya berikut ini.', 'price' => 62100, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/panenHidroponik.png'],
            ['category_id' => 10, 'title' => 'Hidroponik Wick System: Cara Paling Praktis Pasti Panen', 'author' => 'Tintondp', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Keinginan untuk berkebun sayuran sendiri di sekitar rumah membuat tren menanam secara hidroponik semakin meningkat. Selain bisa menyiasati keterbatasan lahan dan kesibukan sehari-hari, bertanam hidroponik juga sering diklaim “bebas kotor” karena tanaman tidak langsung menyentuh tanah. Apalagi, sayuran yang ditanam menggunakan metode hidroponik biasanya lebih cepat panen dibandingkan dengan sayuran yang ditanam dengan metode konvensional.', 'price' => 37800, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/hidroponikWyckSystem.png'],

            ['category_id' => 11, 'title' => 'Sejarah Para Filsuf Dunia', 'author' => 'Ahmad Asnawi', 'publisher' => 'Desa Pustaka Indonesia', 'publish_year' => 2019, 'description' => '*Adam Smith *Aristoteles *Immanuel Kant *Socrates *Alan Turing *Dan masih banyak lagi', 'price' => 30000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/sejarahParafilsufDunia.jpg'],
            ['category_id' => 11, 'title' => 'Tan Malaka: Pandangan Hidup', 'author' => 'Tan Malaka', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Apa artinya menjadi manusia merdeka? Bagaimana seharusnya manusia hidup di tengah dunia yang penuh ketidakadilan, penindasan, dan kebohongan sistemik? Dalam Pandangan Hidup, Tan Malaka menyuguhkan sebuah refleksi mendalam tentang prinsip, arah, dan tujuan hidup manusia-khususnya manusia Indonesia yang sedang merintis jalan kemerdekaannya. Tan Malaka menulis buku ini bukan sebagai seorang filsuf akademik yang berjarak dari realitas, melainkan sebagai pejuang yang berada langsung di jantung pergolakan zaman. Ia menawarkan pandangan hidup yang lahir dari pengalaman revolusi, pengasingan, pembelajaran panjang tentang marxisme, nasionalisme, dan idealisme kemanusiaan. Pandangan Hidup menjadi semacam "kompas moral revolusioner"-penuntun bagi mereka yang tidak hanya ingin hidup, tetapi ingin hidup dengan makna dan keberpihakan yang jelas.', 'price' => 45000, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/tanMalakaPandanganHidup.png'],
            ['category_id' => 11, 'title' => 'Wiji Thukul dalam Sejarah', 'author' => 'Wijayati', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Pada pertengahan 1980-an, Wiji Thukul bergabung dengan berbagai gerakan buruh dan mahasiswa yang menentang ketidakadilan dan penindasan yang dilakukan oleh pemerintah. Dia menggunakan seni sebagai alat perlawanan, percaya bahwa puisi dapat menjadi senjata untuk membangkitkan kesadaran masyarakat.', 'price' => 49500, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/wijiThukul.png'],
            ['category_id' => 11, 'title' => 'RD. Gaos Hardjasoemantri', 'author' => 'Nunus Supardi', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Nama RGH tergolong belum banyak disebut dan ditulis orang. Di dalam buku-buku sejarah kebudayaan Indonesia belum ditemukan tulisan yang mengulas tentang tokoh ini secara khusus meskipun hanya sekilas. Berbeda dengan nama-nama teman seangkatannya seperti HB Jassin, Wiratmo Sukito, Asrul Sani, Sanoesi Pane, Armijn Pane, Sutan Takdir Alisjahbana, Achdiat Kartamihardja, dll, adalah nama-nama yang bertebaran di berbagai tulisan. Bahkan berbeda dengan nama-nama seperti S. Mangunsarkoro, Trisno Sumardjo, Anas Maruf, Mohamad Said, Intojo, Armijn Pane, J.E. Tatengkeng, Mr. Wongsonegoro, yang sama-sama duduk sebagai anggota pengurus BMKN. Menurut penyair Saini KM publikasi di media tentang Pak Gaos terbatas, karena beliau orang penting dalam sejarah kebudayaan tetapi selalu bersikap rendah hati.', 'price' => 125000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/rdGaos.png'],
            ['category_id' => 11, 'title' => 'Raden Saleh (2025)', 'author' => 'Warner Kraus', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Sepak terjang seorang seniman harus dipahami dalam konteks zaman dan lingkungan intelektualnya. Buku ini berupaya mendedahkan kehidupan Raden Saleh dengan cara pandang demikian. Misalnya saja, ada dunia Jawa yang melahirkan Raden Saleh, situasi berbeda yang ditemuinya selama berada di Eropa, atau realitas sosial dan kultural negara kolonial yang semakin kokoh, yang memaksa Sang Pelukis menyesuaikan diri sepulangnya dari Eropa.', 'price' => 187500, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/radenSaleh.png'],

            ['category_id' => 12, 'title' => 'Akuntansi Manajemen: Teori & Riset', 'author' => 'Mahfud Sholihin, Prof., Ph.D., Ak., CA, CPA (Aust) dkk.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Seorang peneliti, terutama positivist, membutuhkan teori dalam membangun logika dalam sebuah riset. Namun, seringkali peneliti kebingungan dalam menentukan teori yang tepat. Buku ini dirancang untuk membantu mengatasi kesulitan tersebut. Setelah mempelajari buku ini, para pembaca, terutama mahasiswa akuntansi, diharapkan dapat memperoleh pemahaman yang mendalam tentang berbagai teori utama dalam penelitian akuntansi manajemen.', 'price' => 129000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/akutansiManajemen.png'],
            ['category_id' => 12, 'title' => '25 Tahun Bank Mandiri Menuju Masa Depan', 'author' => 'Andreas Ismar dkk', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2024, 'description' => '"Semoga Bank Mandiri dapat semakin berkontribusi dalam agenda pembangunan nasional. Menjadi mitra terpercaya UMKM dan pelaku usaha, serta mampu memberikan pelayanan terbaik untuk masyarakat." Ir. H. Joko Widodo, Presiden Republik Indonesia', 'price' => 220698, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/menujuMasaDepan.png'],
            ['category_id' => 12, 'title' => 'E-Business: Bisnis Digital', 'author' => 'Mudjahidin, Andre Parvian A., Kiki Khusna H.', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Selamat datang di buku E-Business: Bisnis Digital: Konsep, Teknologi, Strategi, Implementasi, Analisis Ekonomi. Buku ini disusun untuk memberikan wawasan komprehensif mengenai E-Business yang semakin berkembang di era digital ini. Seiring dengan kemajuan teknologi, khususnya di bidang Kecerdasan Buatan, Blockchain, Internet of Things, Teknologi 5G, Augmented Reality, Virtual Reality, Big Data, dan Cloud Computing, maka dunia bisnis mengalami transformasi besar yang menuntut adaptasi dan inovasi.', 'price' => 169000, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/eBusiness.png'],
            ['category_id' => 12, 'title' => 'Segala Sesuatu yang Perlu Anda Ketahui tentang Ekonomi', 'author' => 'Elaine Schwartz', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2025, 'description' => 'Buku pengantar yang sempurna bagi para mahasiswa dan orang awam, Segala Sesuatu yang Perlu Anda Ketahui tentang EKONOMI menyediakan konsep-konsep yang Anda butuhkan untuk memahami isu-isu mendasar tentang ekonomi. Dilengkapi dengan diagram dan tabel yang bermanfaat, saran untuk bacaan lebih lanjut, dan fitur-fitur yang mudah dipahami tentang para pemikir ekonomi yang hebat sepanjang masa, buku ini membuat pembelajaran ekonomi lebih mudah. Dengan topik yang berkisar dari keseimbangan pasar hingga pembangunan komparatif, buku ini mencakup seluruh bidang ekonomi.', 'price' => 249000, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/segalaSesuatuEkonomi.png'],
            ['category_id' => 12, 'title' => 'Etika Bisnis', 'author' => 'Bakti Sri Rahayu, S.Pd., SE., MM & Devita Putri Anjarsari S.Kom, MM', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2024, 'description' => 'Adapun tujuan utama penyusunan buku: bacaan referensi bacaan terhadap mata kuliah Etika, untuk memudahkan dan menambah wawasan yang sedang mempelajari maupun mendalami bisnis', 'price' => 44000, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/etikaBisnis.png'],

            ['category_id' => 13, 'title' => 'Melody Pop Hits : Piano & Gitar', 'author' => 'Eureka Julius Teruna Ryan', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2023, 'description' => 'Musik pop merupakan musik yang dapat dikenali oleh semua orang dan mudah diterima oleh masyarakat umum khususnya remaja. Selain untuk hiburan, musik pop dapat dijadikan sebagai media belajar untuk berlatih alat musik maupun bernyanyi.', 'price' => 69000, 'stock' => 60, 'is_highlight' => 1, 'cover_image' => 'books/melodyHipHop.png'],
            ['category_id' => 13, 'title' => 'Paket Komplit: Belajar Keyboard Tanpa Guru', 'author' => 'Kiki Laisa', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2015, 'description' => 'Keyboard merupakan instrumen yang sangat luas dan variatif. Dari sebuah keyboard bisa dihasilkan berbagai jenis sound dan berbagai karakter permainan.', 'price' => 75600, 'stock' => 80, 'is_highlight' => 0, 'cover_image' => 'books/belajarKeyboard.jpg'],
            ['category_id' => 13, 'title' => 'Belajar Chord Gitar Dengan Lagu Pop Terbaik Tanpa Guru', 'author' => 'Kiki Laisa', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2018, 'description' => 'Zaman sekarang gak bisa main gitar? Waduh fatal tuh! Yuk belajar dari sekarang! Gampang kok, cukup sediakan gitar dan buku ini. Karena buku ini dibuat untuk membantu bibit-bibit gitaris handal yang belum bisa bermain gitar tapi sangat ingin bisa memainkan gitar dalam waktu yang singkat tanpa privat di tempat musik yang mahal. Materi dalam buku ini 100% dibuat berdasarkan pengalaman penulis yang secara otodidak menekuni alat musik gitar dan sekaligus menjadi bukti nyata.', 'price' => 74700, 'stock' => 35, 'is_highlight' => 0, 'cover_image' => 'books/belajarChordGitar.png'],
            ['category_id' => 13, 'title' => 'Mahir Bermain Gitar Untuk Pemula: Pl Belajar Gitar Secara Otodidak', 'author' => 'Ahmad Faisal Al Kautsar', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2016, 'description' => 'Kamu suka musik? Senang dengan berbagai jenis alat musik? Seperti gitar. Tapi, kamu nggak bisa mainin alat musik tersebut? Mau kursus sekarang mahal biayanya? Alat musik gitar memang sangat populer dan disukai banyak kalangan, baik tua maupun muda, miskin ataupun kaya. Alat musik ini dapat menghasilkan berbagai musik populer yang tentunya sudah tidak asing di telinga kita. Gitar tak hanya sebagai alat untuk menghibur saja, namun juga memberikan kesan keren bagi si pemainnya. Lihat saja musisi yang memegang gitar ketika berada di sebuah konser, mereka terlihat begitu keren dan memesona bukan? Tak hanya musisi saja, orang biasa ketika bisa memainkan gitar akan terlihat sangat keren.', 'price' => 35550, 'stock' => 25, 'is_highlight' => 0, 'cover_image' => 'books/mahirGitar.png'],
            ['category_id' => 13, 'title' => 'Trik Cepat Belajar Gitar Bolong Tanpa Guru', 'author' => 'Adi Jarot Pamungkas', 'publisher' => 'Gramedia Pustaka Utama', 'publish_year' => 2017, 'description' => 'Gitar adalah instrumen musik yang sangat umum dimainkan di berbagai kalangan masyarakat. Lihat saja anak-anak yang sedang nongkrong di warung kopi, pasti mereka memainkan gitar. Hal ini menunjukkan gitar adalah instrumen yang sangat fleksibel.', 'price' => 58500, 'stock' => 30, 'is_highlight' => 0, 'cover_image' => 'books/gitarBolong.png'],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
